// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DAMOCLES_integrate_odeint
NumericVector DAMOCLES_integrate_odeint(const NumericVector& ry, const NumericVector& times, const NumericMatrix& M, double atol, double rtol, std::string stepper);
RcppExport SEXP _DAMOCLES_DAMOCLES_integrate_odeint(SEXP rySEXP, SEXP timesSEXP, SEXP MSEXP, SEXP atolSEXP, SEXP rtolSEXP, SEXP stepperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type ry(rySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type atol(atolSEXP);
    Rcpp::traits::input_parameter< double >::type rtol(rtolSEXP);
    Rcpp::traits::input_parameter< std::string >::type stepper(stepperSEXP);
    rcpp_result_gen = Rcpp::wrap(DAMOCLES_integrate_odeint(ry, times, M, atol, rtol, stepper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DAMOCLES_DAMOCLES_integrate_odeint", (DL_FUNC) &_DAMOCLES_DAMOCLES_integrate_odeint, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DAMOCLES(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
